package npt.map.application.service;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "network")
public class Network {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long nid;
  
  // The user's email
  @NotNull
  private String networkname;
  


  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Network() { }

  public Network(long nid) { 
    this.nid = nid;
  }
  
  
  
  public Network(String networkname) {
 
    this.networkname = networkname;
  }

  // Getter and setter methods

  public long getId() {
    return nid;
  }

  public void setId(long value) {
    this.nid = value;
  }

  public String getNetworkName() {
    return networkname;
  }
  
  public void setNetworkName(String value) {
    this.networkname = value;
  }
  
    
} // class User
